/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.19.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * Forbidden.h
 *
 * Forbidden model
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_Forbidden_H_
#define IO_SWAGGER_CLIENT_MODEL_Forbidden_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Forbidden model
/// </summary>
class  Forbidden
    : public ModelBase
{
public:
    Forbidden();
    virtual ~Forbidden();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Forbidden members

    /// <summary>
    /// Forbidden message
    /// </summary>
    utility::string_t getError() const;
        void setError(utility::string_t value);
    /// <summary>
    /// status code received from SSO
    /// </summary>
    int32_t getSsoStatus() const;
    bool ssoStatusIsSet() const;
    void unsetSso_status();
    void setSsoStatus(int32_t value);

protected:
    utility::string_t m_Error;
        int32_t m_Sso_status;
    bool m_Sso_statusIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_Forbidden_H_ */
