/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.19.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * Service_unavailable.h
 *
 * Service unavailable model
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_Service_unavailable_H_
#define IO_SWAGGER_CLIENT_MODEL_Service_unavailable_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Service unavailable model
/// </summary>
class  Service_unavailable
    : public ModelBase
{
public:
    Service_unavailable();
    virtual ~Service_unavailable();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Service_unavailable members

    /// <summary>
    /// Service unavailable message
    /// </summary>
    utility::string_t getError() const;
        void setError(utility::string_t value);

protected:
    utility::string_t m_Error;
    };

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_Service_unavailable_H_ */
